### ISSUE TITLE
ImportError: module 'piptui' has no attribute 'app'

### ISSUE THREAD

**Issue by singularitti** [nitanmarcel/PipTUI#2]
Hi @nitanmarcel, I have successfully installed [`PipTUI`](https://github.com/nitanmarcel/PipTUI/issues/1). But when I try to run `piptui` (BTW, there is no `pip_tui` command, did you change the command's name from `pip_tui` to `piptui`?), I got such errors:
```python
Traceback (most recent call last):
  File "/Users/qz/.local/pipx/venvs/PipTUI/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2419, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'piptui' has no attribute 'app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/piptui", line 11, in <module>
    load_entry_point('PipTUI==0.1.4', 'console_scripts', 'piptui')()
  File "/Users/qz/.local/pipx/venvs/PipTUI/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/qz/.local/pipx/venvs/PipTUI/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/qz/.local/pipx/venvs/PipTUI/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/qz/.local/pipx/venvs/PipTUI/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2421, in resolve
    raise ImportError(str(exc))
ImportError: module 'piptui' has no attribute 'app'
```
I installed `piptui` to `/usr/local/bin/piptui`, FYI.

**Comment by nitanmarcel** [comment]
Should work. Are you installing the version 0.1.4?

**Comment by singularitti** [comment]
Yes, package PipTUI 0.1.4, Python 3.7.4.

**Comment by singularitti** [comment]
Ah, I create a virtualenv myself, and it works. A bit strange. Maybe it is still `pipx`'s problem.
